[build]
watchPatterns = ["backend/**", "frontend/**"]
buildCommand = "bash build.sh"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "python311", "nodePackages.pnpm"]

[deploy]
startCommand = "bash start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

