[build]
builder = "NIXPACKS"
watchPatterns = [
  "backend/**",
  "frontend/**"
]
buildCommand = "bash build.sh"

[deploy]
startCommand = "bash start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

